project/chat/views.py
from flask import Blueprint, render_template, session
from flask_login import login_required, current_user
from project.models import User, Dialogue, Chat, DoesNotExist, Profile

chat_blueprint = Blueprint('chat', __name__)


@chat_blueprint.route('/inbox')
@login_required
def inbox():
    try:
        s = Dialogue.select().where(Dialogue.user1 == current_user.id)
        r = Dialogue.select().where(Dialogue.user2 == current_user.id)
        u_list = [User.get(User.id == i.user2.id) for i in s]
        for i in r:
            u_list.append(User.get(User.id == i.user1.id))
    except DoesNotExist:
        u_list = None
    return render_template('chat/inbox.html', u_list=u_list)


@chat_blueprint.route('/dialogue/<string:sender>', methods=['GET', 'POST'])
@login_required
def dialogue(sender=None):
    dia = None
    chat = None

    sender_user = User.get(User.username == sender)
    receiver_user = User.get(User.username == current_user.username)
    users = User.raw('select * from user u, dialogue d '
                     'where u.id != %s '
                     'and u.id in (d.user1_id, d.user2_id) '
                     'and %s in (d.user1_id, d.user2_id);', receiver_user.id, receiver_user.id)

    try:
        dia = Dialogue.get(((Dialogue.user1 == sender_user.id) &
                            (Dialogue.user2 == receiver_user.id)) |
                           ((Dialogue.user1 == receiver_user.id) &
                            (Dialogue.user2 == sender_user.id)))
    except DoesNotExist:
        dia = None

    user_profile = Profile.get(Profile.user == sender_user.id)
    current_profile = Profile.get(Profile.user == receiver_user.id)

    if not dia:
        if user_profile.room == 'room2' or current_profile.room == 'room2':
            dia = Dialogue.create(user1=sender_user.id,
                                  user2=receiver_user.id,
                                  exchange=20)
        else:
            dia = Dialogue.create(user1=sender_user.id,
                                  user2=receiver_user.id)
    session['dia'] = dia.id

    chat = Chat.select().where(Chat.dialogue == dia.id)

    if Chat.select().where(Chat.receiver == current_user.id, Chat.was_read == 0).exists():
        query = Chat.update(was_read=True).where(Chat.receiver == current_user.id)
        query.execute()

    count = Chat.select().where(Chat.dialogue == dia.id).count();
    return render_template(
        'chat/dialogue.html',
        users=users, chat=chat, sender=sender, dia=dia, count=count)

project/main/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
import stripe
from project.models import (
    User, Photo, Profile, Friend, Slider,
    DoesNotExist, Subscription, Blog, Visit, BlockList)
from project.profile.form_values import *
from .forms import SearchForm, ContactForm
from project.mailer import send_mail, visit_notif
from project.decorators import no_profile, blocked_user_filter


main_blueprint = Blueprint('main', __name__)
stripe.api_key = "sk_test_KrE8zCZNuf8NUNsgeBLBZwO2"


@main_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        return user_list()
    try:
        slide = Slider.select()
        yesdirect = User.select(User, Profile)\
                        .join(Profile)\
                        .where(Profile.room == 'room1')\
                        .limit(3)
        yestaketime = User.select(User, profile)\
                          .join(Profile)\
                          .where(Profile.room == 'room2')\
                          .limit(3)
    except DoesNotExist:
        slide = None
        yesdirect = None
        yestaketime = None
    return render_template(
        'main/index.html', slide=slide, direct=yesdirect, taketime=yestaketime)


@main_blueprint.route('/about')
def about():
    return render_template('main/about.html')


@main_blueprint.route('/conditions')
def conditions():
    return render_template('main/conditions.html')


@main_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        name = form.nom.data
        email = form.email.data
        message = form.message.data
        telephone = form.telephone.data

        subject = "Yestomeet - Contact"
        html = render_template(
            'email/contact.html', message=message,
            name=name, email=email, telephone=telephone)
        user = 'hamid_kawser@hotmail.be'
        send_mail(user, subject, html)
        return redirect(url_for('main.confirm'))
    return render_template('main/contact.html', form=form)


@main_blueprint.route('/confirm_contact')
def confirm():
    return render_template('main/confirm.html')


@main_blueprint.route('/users')
@login_required
def user_list():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for)
        else:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.id.not_in(blist))
    except DoesNotExist:
        users = None
    return render_template('main/users.html', users=users)


@main_blueprint.route('/profile/<string:username>')
@login_required
@blocked_user_filter
def profile(username):
    try:
        user = User.select(User, Profile)\
                   .join(Profile).where(User.username == username).get()
        p = Profile.get(user=current_user.id)
        try:
            Visit.get(visitor=current_user.id, person=user.id)
        except DoesNotExist:
            Visit.create(visitor=current_user.id, person=user.id)
            if user.notif:
                visit_notif(
                    user.email, current_user.username,
                    user.username, p.slogan)
        friend = Friend.select().where((
            (Friend.friend1 == current_user.id) & (Friend.friend2 == user.id) |
            (Friend.friend1 == user.id) & (Friend.friend2 == current_user.id)))
        if friend.exists():
            photos = Photo.select().where(Photo.user == user.id)
        else:
            photos = Photo.select()\
                          .where(Photo.user == user.id, Photo.private == 0)

    except DoesNotExist:
        user = None
        photos = None
    return render_template(
        'main/profile.html', user=user, photos=photos,
        nationality=dict(nationalities),
        rom=dict(romantic), religion=dict(religion),
        mar=dict(marriage), chil=dict(children), body=dict(body_type),
        st=dict(style), status=dict(marriage_status),
        ori=dict(origin), eye=dict(eyes), hair=dict(hair),
        harle=dict(hair_length), so=dict(smoke),
        have_chil=dict(have_children), live=dict(live),
        job=dict(job), eat=dict(eat), pet=dict(pet),
        speak=dict(speak), edu=dict(education),
        income=dict(income))


@main_blueprint.route('/my_account')
@login_required
@no_profile
def my_account():
    sub = Subscription.select().where(Subscription.user == current_user.id)
    if sub.exists():
        sub = sub.get()
    else:
        sub = None
    user = User.get(User.id == current_user.id)
    gift = current_user.profile.get()
    address = current_user.address.exists()
    if address:
        address = address
    else:
        address = None
    return render_template(
        'main/my_account.html', sub=sub, user=user,
        profile=gift, address=address)


@main_blueprint.route('/blog')
def blog():
    posts = Blog.select().order_by(Blog.created_at.desc())
    if posts.exists():
        posts = posts
    else:
        posts = None
    return render_template('main/blog.html', posts=posts)


@main_blueprint.route('/blog/<int:id>')
def article(id):
    post = Blog.get(Blog.id == id)
    return render_template('main/article.html', post=post)


@main_blueprint.route('/visit')
@login_required
def visit():
    visit_list = Visit.select()\
                      .where(Visit.person == current_user.id)\
                      .order_by(Visit.created_at.desc())
    if visit_list.exists():
        visit_list = visit_list
    else:
        visit_list = None
    if Visit.select()\
            .where(Visit.person == current_user.id, Visit.read == 0).exists():
        query = Visit.update(read=True).where(Visit.person == current_user.id)
        query.execute()

    return render_template('main/visit.html', visit_list=visit_list)


@main_blueprint.route('/gift_items')
@login_required
def gift_items():
    receiver = request.args.get('user')
    user = User.get(User.id == receiver)
    return render_template('main/items.html', receiver=receiver, user=user)


@main_blueprint.route('/gift_charge', methods=['POST'])
def gift_charge():
    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken']
    )

    stripe.Charge.create(
        customer=customer.id,
        amount=request.form['amount'],
        currency='eur'
    )
    user = User.get(User.id == int(request.form['user']))
    return render_template('main/send.html', user=user)


@main_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        age_min = int(form.age_min.data)
        age_max = int(form.age_max.data)
        gender = form.gender.data

        users = User.select().where(User.age.between(age_min, age_max),
                                    User.gender == gender,
                                    User.id != current_user.id)
        return render_template(
            'main/users.html',
            users=users)
    return render_template('main/search.html', form=form)


@main_blueprint.route('/online_users')
def online_users():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.online == 1)
        else:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.id.not_in(blist),
                            User.online == 1)
    except DoesNotExist:
        users = None
    return render_template(
        'main/users.html',
        users=users,
        dsc="Voici les utilisateurs actuellement en ligne.Envoyez vite un petit message à ceux qui vous font craquer.")


@main_blueprint.route('/yestaketime')
def yestaketime():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room2')
        else:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room2',
                            User.id.not_in(blist))
    except DoesNotExist:
        users = None
    return render_template('main/users.html', users=users)


@main_blueprint.route('/yestobedirect')
def yestobedirect():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room1')
        else:
            users = User.select()\

project/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title%} {% endblock %} - Yes To Meet You</title>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/pepper-grinder/jquery-ui.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/stripe.css')}}">
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script src="https://js.stripe.com/v3/"></script>
        <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
        <link rel="stylesheet" href="../static/css/emojionearea.css">
        <script src="../static/js/emojionearea.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/chat.js') }}"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        {% include 'nav.html' %}
        {% if current_user.is_authenticated %}
            {% include 'user_nav.html' %}
        {% endif %}     
        <div class="container">
            {% block content %}{% endblock%}
        </div>
        {% include 'social.html' %}
        <footer>
            <div class="content condition">
                <p class="has-text-centered"> <a href="{{url_for('main.conditions')}}" class="text-white">{{ _("Conditions générales d'utilisation C.G.U")}}</a></p>
            </div>
            <div class="content copyright">
                <p class="has-text-centered">Copyright © yestomeetyou.com 2017. {{ _("Tous les droits sont réservés")}}</p>
            </div>
        </footer>
        <script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>  
        <script src="{{ url_for('static', filename='js/birthdate.js') }}"></script>
        <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
        <script id="dsq-count-scr" src="//yestomeet.disqus.com/count.js" async></script>
    </body>
</html>

project/templates/nav.html
<nav class="navbar">
  <div class="container">
        <div class="navbar-brand">
            <div class="navbar-item">
                <a href="/" class="brand-logo">
                    <img src="../static/img/logo.svg" alt="Yestomeetyou" width="250">
                </a>
            </div>
            <div class="navbar-item nav-text is-hidden-mobile">
                <p style="font-size: 24px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
            <div class="navbar-burger" data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="navbar-menu" id="navMenu">
            <div class="navbar-end">
                <a href="/about" class="navbar-item {% if request.path == '/about' %}active{% endif %}">{{ _('À propos')}}</a>
                {% if not current_user.is_authenticated %}
                    <a href="{{ url_for('user.register')}}" class="navbar-item {% if request.path == '/register' %}active{% endif %}">{{ _('S\'enregistrer')}}</a>
                    <a href="{{ url_for('user.login') }}" class="navbar-item {% if request.path == '/login' %}active{% endif %}">{{ _('Déjà membre')}}</a>
                {% endif %}
                <div class="is-hidden-desktop is-hidden-widescreen is-hidden-tablet">
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('profile.profile')}}" class="navbar-item {% if request.path == '/profile' %}active{% endif %}">{{ _('Profil')}}</a>
                        <a href="{{url_for('main.online_users')}}" class="navbar-item {% if request.path == '/online_users' %}active{% endif %}">{{ _('En Ligne')}}</a>
                        <a href="{{url_for('main.yestaketime')}}" class="navbar-item {% if request.path == '/yestaketime' %}active{% endif %}">{{ _('YesToTakeTime')}}</a>
                        <a href="{{url_for('main.yestobedirect')}}" class="navbar-item {% if request.path == '/yestobedirect' %}active{% endif %}">{{ _('YesToBeDirect')}}</a>
                        <a href="{{url_for('main.search')}}" class="navbar-item {% if request.path == '/search' %}active{% endif %}">{{ _('Recherche')}}</a>
                        <a href="{{url_for('main.visit')}}" class="navbar-item {% if request.path == '/visit' %}active{% endif %}">{{ _('Visit')}}</a>
                        <a href="{{url_for('chat.inbox')}}" class="navbar-item {% if request.path == '/inbox' %}active{% endif %}">{{ _('Messages')}}</a>
                        <a href="{{url_for('main.my_account')}}" class="navbar-item {% if request.path == '/my_account' %}active{% endif %}">{{ _('préférence')}}</a>
                        <a href="{{ url_for('user.logout') }}" class="navbar-item">{{ _('Déconnexion')}}</a>
                    {% endif %}
                </div>
                <a href="/blog" class="navbar-item {% if request.path == '/blog' %}active{% endif %}">{{ _('Blog') }}</a>
                <a href="/contact" class="navbar-item {% if request.path == '/contact' %}active{% endif %}">{{ _('Contact')}}</a> 
            </div>
        </div>
  </div>
</nav>

project/templates/social.html
<div class="container sandbox is-hidden-mobile" style="margin-top: 20vh;">
            <div class="tile is-ancestor">
                <div class="tile is-vertical is-6">
                    <div class="tile is-parent">
                        <article class="tile is-child notification is-white">
                            <div class="content level">
                                <div class="level-left">
                                    <div class="level-item">
                                        <figure>                            
                                            <img src="../static/img/apple.svg" width="200" alt="apple">
                                        </figure>
                                        <figure style="margin-top: -33px;">                            
                                            <img src="../static/img/play.svg" width="200" alt="google play">
                                        </figure> 
                                    </div>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
                <div class="tile is-parent">
                    <article class="tile is-child notification is-white">
                        <figure class="image is-64x64 social">                            
                            <img src="../static/img/instagrame-fonce.svg" alt="instagram">
                        </figure>
                        <figure class="image is-64x64 social">
                            <img src="../static/img/facebook-fonce.svg" alt="facebook">
                        </figure>
                        <figure class="image is-64x64 social">
                            <img src="../static/img/twitter-fonce.svg" alt="twitter">
                        </figure>
                    </article>
                </div>
            </div>
        </div>

project/templates/user_nav.html
<nav class="navbar user_nav is-hidden-mobile">
    <div class="container">
        <div class="navbar-brand">
            <div class="navbar-burger" data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="navbar-menu">
            <a href="{{ url_for('profile.profile')}}" class="navbar-item {% if request.path == '/profile' %}active{% endif %}">{{ _('Votre profil')}}</a>
            <a href="{{url_for('main.online_users')}}" class="navbar-item {% if request.path == '/online_users' %}active{% endif %}">{{ _('En ligne')}}</a>
            <a href="{{url_for('main.yestaketime')}}" class="navbar-item {% if request.path == '/yestaketime' %}active{% endif %}">{{ _('YesToTakeTime')}}</a>
            <a href="{{url_for('main.yestobedirect')}}" class="navbar-item {% if request.path == '/yestobedirect' %}active{% endif %}">{{ _('YesToBeDirect')}}</a>
            <a href="{{url_for('main.search')}}" class="navbar-item {% if request.path == '/search' %}active{% endif %}">{{ _('Rechercher')}}</a>
            <a href="{{url_for('main.visit')}}" class="navbar-item {% if request.path == '/visit' %}active{% endif %}">{{ _('Vos visites')}}</a>
            <a href="{{url_for('chat.inbox')}}" class="navbar-item {% if request.path == '/inbox' %}active{% endif %}">{{ _('Messages')}}</a>
            <div class="navbar-end">
                <a href="{{url_for('main.my_account')}}" class="navbar-item {% if request.path == '/my_account' %}active{% endif %}">{{ _('préférence')}}</a>
                <a href="{{ url_for('user.logout') }}" class="navbar-item">{{ _('Déconnexion')}}</a>
            </div>
        </div>
    </div>
</nav>