project/profile/views.py
from uuid import uuid4
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from project.models import (
    Profile, Photo, database,
    IntegrityError, DoesNotExist, Address)
from .forms import (
    ProfileForm, UploadForm, AddressForm, ProfileUpdateForm)
from .helpers import upload_file_to_s3, delete_file_from_s3
from .form_values import *
from project.decorators import no_profile, profile_exist


profile_blueprint = Blueprint('profile', __name__)


@profile_blueprint.route('/new_profile', methods=['GET', 'POST'])
@login_required
# @profile_exist
def new_profile():
    form = ProfileForm()
    if form.validate_on_submit():
        try:
            with database.transaction():
                Profile.create(
                    user=current_user._get_current_object(),
                    room=form.room.data,
                    gift=form.gift.data,
                    description=form.description.data,
                    romantic=form.romantic.data,
                    marriage=form.marriage.data,
                    want_children=form.want_children.data,
                    nationality=form.nationality.data,
                    height=form.height.data,
                    body_type=form.body_type.data,
                    style=form.style.data,
                    origin=form.origin.data,
                    eyes=form.eyes.data,
                    hair=form.hair.data,
                    hair_length=form.hair_length.data,
                    weight=form.weight.data,
                    status=form.status.data,
                    smoke=form.smoke.data,
                    children=form.children.data,
                    live=form.live.data,
                    job=form.job.data,
                    eat=form.eat.data,
                    pet=form.pet.data,
                    speak1=form.speak1.data,
                    speak2=form.speak2.data,
                    speak3=form.speak3.data,
                    speak4=form.speak4.data,
                    education=form.education.data,
                    religion=form.religion.data,
                    income=form.income.data,
                    slogan=form.slogan.data,
                    first_meet=form.first_meet.data,
                    quality=form.quality.data,
                    defauts=form.defauts.data,
                    dream=form.dream.data,
                    love=form.love.data,
                    partner=form.partner.data,
                    loisir=form.loisir.data,
                    friend=form.friend.data,
                    experience=form.experience.data,
                    boulot=form.experience.data,
                    animal=form.animal.data,
                    enfant=form.enfant.data,
                    future=form.future.data,
                    fierte=form.fierte.data,
                    culture=form.culture.data,
                    malaise=form.malaise.data,
                    sortie=form.sortie.data,
                    voyage=form.voyage.data,
                    addication=form.addication.data,
                    passion=form.passion.data
                )
                photo = form.photo.data
                generated_name = uuid4().hex
                photo.filename = secure_filename(generated_name + photo.filename)
                output = upload_file_to_s3(
                    photo,
                    'yestomeetyou')
                p = Photo(
                    url=str(output),
                    user=current_user._get_current_object(),
                    default=True)
                if form.room.data == 'room2':
                    p.private = True
                    p.save()
                if form.gift.data == 1:
                    return redirect(url_for('profile.address'))
                return redirect(url_for('profile.profile'))
        except IntegrityError:
            flash('Unable to create profile', 'danger')

    return render_template('profile/new-profile.html', form=form)


@profile_blueprint.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    profile = Profile.get(Profile.user == current_user.id)
    form = ProfileUpdateForm(obj=profile)
    if form.validate_on_submit():
        try:
            with database.transaction():
                p = Profile(
                    user=current_user._get_current_object(),
                    gift=form.gift.data,
                    room=form.room.data,
                    description=form.description.data,
                    romantic=form.romantic.data,
                    marriage=form.marriage.data,
                    want_children=form.want_children.data,
                    nationality=form.nationality.data,
                    height=form.height.data,
                    body_type=form.body_type.data,
                    style=form.style.data,
                    origin=form.origin.data,
                    eyes=form.eyes.data,
                    hair=form.hair.data,
                    hair_length=form.hair_length.data,
                    weight=form.weight.data,
                    status=form.status.data,
                    smoke=form.smoke.data,
                    children=form.children.data,
                    live=form.live.data,
                    job=form.job.data,
                    eat=form.eat.data,
                    pet=form.pet.data,
                    speak1=form.speak1.data,
                    speak2=form.speak2.data,
                    speak3=form.speak3.data,
                    speak4=form.speak4.data,
                    education=form.education.data,
                    religion=form.religion.data,
                    income=form.income.data,
                    slogan=form.slogan.data,
                    first_meet=form.first_meet.data,
                    quality=form.quality.data,
                    defauts=form.defauts.data,
                    dream=form.dream.data,
                    love=form.love.data,
                    partner=form.partner.data,
                    loisir=form.loisir.data,
                    friend=form.friend.data,
                    experience=form.experience.data,
                    boulot=form.experience.data,
                    animal=form.animal.data,
                    enfant=form.enfant.data,
                    future=form.future.data,
                    fierte=form.fierte.data,
                    culture=form.culture.data,
                    malaise=form.malaise.data,
                    sortie=form.sortie.data,
                    voyage=form.voyage.data,
                    addication=form.addication.data,
                    passion=form.passion.data
                )
                p.save()
                if form.room.data == 'room1':
                    photo = Photo.select().where(Photo.user == current_user.id)
                    for p in photo:
                        p.private = False
                        p.save()
                flash('Your profile has been updated!')
                return redirect(url_for('profile.profile'))
        except IntegrityError:
            flash('Unable to create profile', 'danger')

    return render_template('profile/edit-profile.html', form=form)


@profile_blueprint.route('/profile')
@login_required
@no_profile
def profile():
    profile = Profile.get(Profile.user == current_user.id)
    try:
        photo = Photo.select()\
                     .where(Photo.user == current_user.id, Photo.default == 1)\
                     .get()
        photos = Photo.select().where(Photo.user == current_user.id)
    except DoesNotExist:
        photo = None
        photos = None
    return render_template(
        'profile/profile.html',
        profile=profile, nationality=dict(nationalities),
        rom=dict(romantic), religion=dict(religion),
        mar=dict(marriage), chil=dict(children), body=dict(body_type),
        st=dict(style), status=dict(marriage_status),
        ori=dict(origin), eye=dict(eyes), hair=dict(hair),
        harle=dict(hair_length), so=dict(smoke),
        have_chil=dict(have_children), live=dict(live),
        job=dict(job), eat=dict(eat), pet=dict(pet),
        speak=dict(speak), edu=dict(education),
        income=dict(income), photo=photo, photos=photos)


def get_room():
    p = Profile.get(Profile.user == current_user.id)
    return p.room == 'room2'


@profile_blueprint.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if form.validate_on_submit():
        photo = form.photo.data
        generated_name = uuid4().hex
        photo.filename = secure_filename(generated_name + photo.filename)
        output = upload_file_to_s3(
            photo,
            'yestomeetyou')
        p = Photo(
            url=str(output),
            user=current_user._get_current_object())
        if get_room():
            p.private = True
        p.save()
    try:
        photo = Photo.select().where(Photo.user == current_user.id)
    except DoesNotExist:
        photo = None
    return render_template('profile/upload.html', form=form, photo=photo)


@profile_blueprint.route('/delete_pic/<int:id>')
@login_required
def delete_pic(id):
    p = Photo.get(Photo.id == id)
    delete_file_from_s3('yestomeetyou', '{}'.format(p.url))
    p.delete_instance()
    return redirect(url_for('profile.upload'))


@profile_blueprint.route('/pic_set/<int:id>')
@login_required
def set_profile_pic(id):
    pro = Photo.get(Photo.id == id)
    try:
        pic = Photo.select()\
                   .where(Photo.user == current_user.id, Photo.default == 1)\
                   .get()
        if pic.default:
            pic.default = False
            pic.save()
            pro.default = True
            pro.save()
    except DoesNotExist:
        pro.default = True
        pro.save()
    return redirect(url_for('profile.upload'))

project/templates/profile/address.html
{% from 'macros/_render_input.html' import render_input %}

{% extends 'layout.html' %}

{% block content %}
    
<section class="container">
    <div class="columns">
        <div class="column is-three-fifths is-offset-one-fifth">
            <section class="section">
            <p class="title is-3" style="color: #000 !important;">{{ _('Ajouter votre adresse')}}</p>
            <div class="content">
                <p>{{ _('En acceptant, vous acceptez les conditions et procédures de Yes To Meet You. Si quelqu’un vous offre des fleurs ou des chocolats, le site vous contactera par e-mail ou par téléphone afin d’obtenir votre accord et de confirmer les données de livraison. (Elles peuvent être différentes de votre adresse d’inscription.)')}}</p>
                <p><strong>{{ _('Vos coordonnées ne seront en aucun cas transmises à des tiers.') }}</strong></p>
            </div>
            <div class="is-divider"></div>
            <form action="" method="POST">
                {{ form.csrf_token }}
                {{ render_input(form.name)}}
                {{ render_input(form.street)}}
                {{ render_input(form.postal_code)}}
                {{ render_input(form.country)}}
                {{ render_input(form.telephone)}}
                <div class="field">
                    <button type="submit" class="button">{{ _('Ajouter')}}</button>
                </div>
            </form>
            </section>
        </div>
    </div>
</section>

{% endblock %}

project/templates/profile/profile.html
{% extends 'layout.html' %}

{% block title %}Votre Profile{% endblock %}
{% block content %}
    <section>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
              <div class="notification is-danger">
                <button class="delete"></button>
                {{ message }}
              </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
        <div class="columns">
            <div class="column is-one-quarter">
                <section class="section">
                    {% if photo == None %}
                        <p><a class="text-red" href="{{url_for('profile.upload')}}">{{ _('Ajouter un photo')}}</a></p>
                    {% else %}
                        <figure class="image is-3by2">
                            <img src="http://yestomeetyou.s3.amazonaws.com/{{photo.url}}">
                        </figure>
                        <div class="columns is-multiline is-mobile" style="margin-top: .75rem;">
                            {% if photos != None %}
                                {% for photo in photos %}
                                    <div class="column is-one-quarter">
                                        <figure>
                                            <a data-fancybox="gallery" href="http://yestomeetyou.s3.amazonaws.com/{{photo.url}}">
                                                <img src="http://yestomeetyou.s3.amazonaws.com/{{photo.url}}">
                                            </a>
                                        </figure>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <p><a class="text-red" href="{{url_for('profile.upload')}}">{{ _('Ajouter un photo')}}</a></p>
                    {% endif %}
                </section>
                <div class="is-hidden-tablet is-hidden-desktop is-hidden-widescreen is-hidden-fullhd">
                    <div class="section">
                        <p><a href="/inbox" class="visit text-red" style="float: left;">{{g.msg_count}} {{ _('messages')}} <i class="fa fa-envelope-o"></i> </a><a href="/visit" class="visit text-red" style="float: right;">{{g.count}} {{ _('Visits')}} <i class="fa fa-users" aria-hidden="true"></i></a></p>
                        
                    </div>
                    <section class="my-account section">
                        <p class="subtitle gift-text text-white "> {{_('Bienvenue')}} {{ profile.user.username }}</p>
                        <p><a class="text-red" href="{{url_for('profile.edit_profile')}}">{{ _('Éditer mon profil')}} <i class="fa fa-pencil" aria-hidden="true"></i></a></p>
                    </section>
                </div>
                <div class="is-hidden-mobile">
                    <p class="gift-text text-white"> {{ _('Une photo à votre image.')}}<i class="fa fa-camera-retro fa-2x icon-position" aria-hidden="true"></i></p>
                    <p class="subtitle"> {{ _('Sublimez votre profil.')}}</p>
                    <p class="content">{{ _('Une mauvaise photo peut tout gâcher. Trouvez facilement le photographe qui révèlera au monde votre beauté intérieure.')}}</p>
                    <button class="button">{{ _('Chercher un photographe')}}</button>
                </div>
            </div>
            <div class="column">
                <section class="section">
                    <p class="title is-5">{{ _('Description')}} </p>
                    <p class="content">{{ profile.description }}</p>

                    <p class="title is-5">{{ _('Votre slogan')}}</p>
                    <p class="content">{{ profile.slogan }}</p>

                    <p class="title is-5">{{ _('Premier rendez-vous')}}</p>
                    <p class="content">{{ profile.first_meet }}</p>

                    <p class="title is-5">{{ _('Qualités')}}</p>
                    <p class="content">{{ profile.quality }}</p>

                    <p class="title is-5">{{ _('Défauts')}}</p>
                    <p class="content">{{ profile.defauts }}</p>

                    <p class="title is-5">{{ _('Rêves')}}</p>
                    <p class="content">{{ profile.dream }}</p>

                    <p class="title is-5">{{ _('Amour')}}</p>
                    <p class="content">{{ profile.love }}</p>

                    <p class="title is-5">{{ _('Partenaire')}}</p>
                    <p class="content">{{ profile.partner }}</p>

                    <p class="title is-5">{{ _('Loisirs')}}</p>
                    <p class="content">{{ profile.loisir }}</p>

                    <p class="title is-5">{{ _('Amis')}}</p>
                    <p class="content">{{ profile.friend }}</p>

                    <p class="title is-5">{{ _('Expérience forte')}}</p>
                    <p class="content">{{ profile.experience }}</p>

                    <p class="title is-5">{{ _('Boulot')}}</p>
                    <p class="content">{{ profile.boulot }}</p>

                    <p class="title is-5">{{ _('Animaux')}}</p>
                    <p class="content">{{ profile.animal }}</p>

                    <p class="title is-5">{{ _('Enfants')}}</p>
                    <p class="content">{{ profile.enfant }}</p>

                    <p class="title is-5">{{ _('Avenir')}}</p>
                    <p class="content">{{ profile.future }}</p>

                    <p class="title is-5">{{ _('Fierté')}}</p>
                    <p class="content">{{ profile.fierte }}</p>

                    <p class="title is-5">{{ _('Culture')}}</p>
                    <p class="content">{{ profile.culture }}</p>

                    <p class="title is-5">{{ _('Malaise')}}</p>
                    <p class="content">{{ profile.malaise }}</p>

                    <p class="title is-5">{{ _('Sorties')}}</p>
                    <p class="content">{{ profile.sortie }}</p>

                    <p class="title is-5">{{ _('Voyages')}}</p>
                    <p class="content">{{ profile.voyage }}</p>

                    <p class="title is-5">{{ _('Addictions')}}</p>
                    <p class="content">{{ profile.addication }}</p>

                    <p class="title is-5">{{ _('Passions')}}</p>
                    <p class="content">{{ profile.passion }}</p>
                </section>
                <section class="section profile-padding">
                    <div class="is-divider" data-content="Caractère"></div>
                    <h3 class="title is-6">{{ _('Bon à savoir :')}}</h3>
                    <p>{{ _('Romantique')}} : {{ rom[profile.romantic]}}</p>
                    <p>{{ _('Pour moi le mariage c\'est')}} : {{ mar[profile.marriage]}}</p>
                </section>
                <section class="section profile-padding">
                    <div class="is-divider" data-content="Apparence"></div>
                    <h3 class="title is-6">{{ _('Ces détails qui ne comptent pas ☺:')}}</h3>
                    <p>{{ _('Ma taille')}} : {{ profile.height}}</p>
                    <p>{{ _('Mon poids')}} : {{ profile.weight}}</p>
                    <p>{{ _('Mes cheveux')}} : {{ hair[profile.hair]}}</p>
                    <p>{{ _('Longueur de mes cheveux')}} : {{ harle[profile.hair_length]}}</p>
                    <p>{{ _('Mon style')}} : {{ st[profile.style]}}</p>
                    <p>{{ _('Ma silhouette')}} : {{ body[profile.body_type]}}</p>
                </section>
                <section class="section profile-padding">
                    <div class="is-divider" data-content="Style de vie"></div>
                    <h3 class="title is-6">{{ _('C’est ma vie !')}}</h3>
                    <p>{{ _('Mon statut marital')}} : {{ status[profile.status]}}</p>
                    <p>{{ _('Je vis')}} : {{ live[profile.live]}}</p>
                    <p>{{ _('Je veux des enfants')}} : {{ chil[profile.want_children]}}</p>
                    <p>{{ _('Mon origine')}} : {{ ori[profile.origin]}}</p>
                    <p>{{ _('Mes yeux')}} : {{ eye[profile.eyes]}}</p>
                </section>
                <section class="section profile-padding">
                    <div class="is-divider" data-content="Origines"></div>
                    <p>{{ _('Ma religion')}} : {{ religion[profile.religion]}}</p>
                    <p>{{ _('Ma nationalité')}} : {{ nationality[profile.nationality]}}</p>
                </section>
                
                <section class="section profile-padding">
                    <div class="is-divider" data-content="Autres"></div>
                    <p>{{ _('Je fume')}} : {{ so[profile.smoke]}}</p>
                    <p>{{ _('J\'ai des enfants')}} : {{ have_chil[profile.children]}}</p>
                    <p>{{ _('Ma profession')}} : {{ job[profile.job]}}</p>
                    <p>{{ _('Je mange')}} : {{ eat[profile.eat]}}</p>
                    <p>{{ _('Mes animaux de compagnie')}} : {{ pet[profile.pet]}}</p>
                    <p>{{ _('Je parle')}} : {{profile.speak1}}, {{profile.speak2}}, {{profile.speak3}}, {{profile.speak4}} </p>
                    <p>{{ _('Quelles études avez-vous faites?')}} : {{ edu[profile.education]}}</p>
                    <p>{{ _('Mes revenus')}} : {{ income[profile.income]}}</p>
                </section>
            </div>
            <div class="column is-one-fifth is-hidden-mobile">
                <div class="section">
                    <p><a href="/inbox" class="visit text-red" style="float: left; font-size: 18px;">{{g.msg_count}} {{ _('messages')}} <i class="fa fa-envelope-o"></i> </a><a href="/visit" class="visit text-red" style="float: right; font-size: 18px;">{{g.count}} {{ _('Visits')}} <i class="fa fa-users" aria-hidden="true"></i></a></p>
                </div>
                <section class="my-account">
                    <p class="subtitle gift-text text-white ">{{_('Bienvenue')}} {{ profile.user.username }} <i class="fa fa-circle icon-position" style="color: #95c11f; margin-top: 4px !important;" aria-hidden="true"></i></p>
                    <p><a class="text-red" href="{{url_for('profile.edit_profile')}}">{{ _('Éditer mon profil')}} <i class="fa fa-pencil" aria-hidden="true"></i></a></p>
                </section>

                <div class="">
                    <h3 class=" gift-text text-white">{{ _('Faire une surprise.')}} <i class="fa fa-gift fa-2x icon-position" aria-hidden="true"></i></h3>
                        <p class="subtitle"> {{ _('Envoyez un vrai cadeau')}}</p>
                        <p class="content">{{ _('Une surprise, ça fait toujours plaisir. Epatez l’élu de votre cœur en lui envoyant des fleurs ou des chocolats en vrai.')}}</p>
                        <figure class="">
                            <img src="../static/img/choclat.jpg" alt="choclat" width="320px">
                        </figure>
                        <button class="button"><a class="text-white" href="/">{{ _('Envoyer un cadeau')}}</a></button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

project/templates/profile/upload.html
{% extends 'layout.html' %}

{% block content %}
    <section class="section">
    <div class="columns is-mobile">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <h3 class="title">{{ _('Ajouter un photo') }}</h3>
            <form method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="field">
                    {{ form.photo()}}
                    {% for error in form.photo.errors %}
                      <p class="help is-danger" >{{ error }}</p>
                    {% endfor %}
                    <p id = "er" class="help is-danger" style="display: none;">{{ _('Poids du fichier est trop grand')}}</p>
                </div>
                            
                <button type="submit" class="button">{{ _('Ajouter un photo') }}</button>
            </form>
        </div>
    </div>
        {% if photo != None %}
            <div class="columns is-multiline is-mobile">
            {% for p in photo %}
                    <div class="column is-one-fifth-desktop is-half-mobile">
                        <figure class="image">
                            <img src="http://yestomeetyou.s3.amazonaws.com/{{p.url}}">
                        </figure>
                        {% if not p.default %} 
                            <a class="button" href="{{url_for('profile.set_profile_pic',id=p.id)}}">{{ _('Définir la photo de profil')}}</a>
                            <a class="button" href="{{url_for('profile.delete_pic',id=p.id)}}">{{ _('supprimer')}}</a>
                        {% endif%}
                    </div>
                
            {% endfor %}
        {% endif %}
        </div>
</section>
{% endblock %}