project/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, IntegerField,
    SelectField, TextAreaField)
from wtforms.validators import DataRequired, Email, Length
from flask_babel import gettext


class SearchForm(FlaskForm):
    age_min = SelectField(
        gettext('min'),
        coerce=int,
        choices=[(i, f"{i}") for i in range(18, 99)])
    age_max = SelectField(
        gettext('max'),
        coerce=int,
        choices=[(i, f"{i}") for i in range(18, 99)])
    gender = SelectField(
        gettext('sexe'),
        choices=[('men', gettext('un homme')), ('women', gettext('une femme'))])


class ContactForm(FlaskForm):
    nom = StringField(gettext('Votre nom'), validators=[DataRequired()])
    email = StringField(
        gettext('Votre email'), validators=[DataRequired()])
    telephone = StringField(gettext('Votre Téléphone'))
    message = TextAreaField(
        gettext('Votre message'), validators=[DataRequired(), Length(min=25)])

project/main/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
import stripe
from project.models import (
    User, Photo, Profile, Friend, Slider,
    DoesNotExist, Subscription, Blog, Visit, BlockList)
from project.profile.form_values import *
from .forms import SearchForm, ContactForm
from project.mailer import send_mail, visit_notif
from project.decorators import no_profile, blocked_user_filter


main_blueprint = Blueprint('main', __name__)
stripe.api_key = "sk_test_KrE8zCZNuf8NUNsgeBLBZwO2"


@main_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        return user_list()
    try:
        slide = Slider.select()
        yesdirect = User.select(User, Profile)\
                        .join(Profile)\
                        .where(Profile.room == 'room1')\
                        .limit(3)
        yestaketime = User.select(User, profile)\
                          .join(Profile)\
                          .where(Profile.room == 'room2')\
                          .limit(3)
    except DoesNotExist:
        slide = None
        yesdirect = None
        yestaketime = None
    return render_template(
        'main/index.html', slide=slide, direct=yesdirect, taketime=yestaketime)


@main_blueprint.route('/about')
def about():
    return render_template('main/about.html')


@main_blueprint.route('/conditions')
def conditions():
    return render_template('main/conditions.html')


@main_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        name = form.nom.data
        email = form.email.data
        message = form.message.data
        telephone = form.telephone.data

        subject = "Yestomeet - Contact"
        html = render_template(
            'email/contact.html', message=message,
            name=name, email=email, telephone=telephone)
        user = 'hamid_kawser@hotmail.be'
        send_mail(user, subject, html)
        return redirect(url_for('main.confirm'))
    return render_template('main/contact.html', form=form)


@main_blueprint.route('/confirm_contact')
def confirm():
    return render_template('main/confirm.html')


@main_blueprint.route('/users')
@login_required
def user_list():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for)
        else:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.id.not_in(blist))
    except DoesNotExist:
        users = None
    return render_template('main/users.html', users=users)


@main_blueprint.route('/profile/<string:username>')
@login_required
@blocked_user_filter
def profile(username):
    try:
        user = User.select(User, Profile)\
                   .join(Profile).where(User.username == username).get()
        p = Profile.get(user=current_user.id)
        try:
            Visit.get(visitor=current_user.id, person=user.id)
        except DoesNotExist:
            Visit.create(visitor=current_user.id, person=user.id)
            if user.notif:
                visit_notif(
                    user.email, current_user.username,
                    user.username, p.slogan)
        friend = Friend.select().where((
            (Friend.friend1 == current_user.id) & (Friend.friend2 == user.id) |
            (Friend.friend1 == user.id) & (Friend.friend2 == current_user.id)))
        if friend.exists():
            photos = Photo.select().where(Photo.user == user.id)
        else:
            photos = Photo.select()\
                          .where(Photo.user == user.id, Photo.private == 0)

    except DoesNotExist:
        user = None
        photos = None
    return render_template(
        'main/profile.html', user=user, photos=photos,
        nationality=dict(nationalities),
        rom=dict(romantic), religion=dict(religion),
        mar=dict(marriage), chil=dict(children), body=dict(body_type),
        st=dict(style), status=dict(marriage_status),
        ori=dict(origin), eye=dict(eyes), hair=dict(hair),
        harle=dict(hair_length), so=dict(smoke),
        have_chil=dict(have_children), live=dict(live),
        job=dict(job), eat=dict(eat), pet=dict(pet),
        speak=dict(speak), edu=dict(education),
        income=dict(income))


@main_blueprint.route('/my_account')
@login_required
@no_profile
def my_account():
    sub = Subscription.select().where(Subscription.user == current_user.id)
    if sub.exists():
        sub = sub.get()
    else:
        sub = None
    user = User.get(User.id == current_user.id)
    gift = current_user.profile.get()
    address = current_user.address.exists()
    if address:
        address = address
    else:
        address = None
    return render_template(
        'main/my_account.html', sub=sub, user=user,
        profile=gift, address=address)


@main_blueprint.route('/blog')
def blog():
    posts = Blog.select().order_by(Blog.created_at.desc())
    if posts.exists():
        posts = posts
    else:
        posts = None
    return render_template('main/blog.html', posts=posts)


@main_blueprint.route('/blog/<int:id>')
def article(id):
    post = Blog.get(Blog.id == id)
    return render_template('main/article.html', post=post)


@main_blueprint.route('/visit')
@login_required
def visit():
    visit_list = Visit.select()\
                      .where(Visit.person == current_user.id)\
                      .order_by(Visit.created_at.desc())
    if visit_list.exists():
        visit_list = visit_list
    else:
        visit_list = None
    if Visit.select()\
            .where(Visit.person == current_user.id, Visit.read == 0).exists():
        query = Visit.update(read=True).where(Visit.person == current_user.id)
        query.execute()

    return render_template('main/visit.html', visit_list=visit_list)


@main_blueprint.route('/gift_items')
@login_required
def gift_items():
    receiver = request.args.get('user')
    user = User.get(User.id == receiver)
    return render_template('main/items.html', receiver=receiver, user=user)


@main_blueprint.route('/gift_charge', methods=['POST'])
def gift_charge():
    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken']
    )

    stripe.Charge.create(
        customer=customer.id,
        amount=request.form['amount'],
        currency='eur'
    )
    user = User.get(User.id == int(request.form['user']))
    return render_template('main/send.html', user=user)


@main_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        age_min = int(form.age_min.data)
        age_max = int(form.age_max.data)
        gender = form.gender.data

        users = User.select().where(User.age.between(age_min, age_max),
                                    User.gender == gender,
                                    User.id != current_user.id)
        return render_template(
            'main/users.html',
            users=users)
    return render_template('main/search.html', form=form)


@main_blueprint.route('/online_users')
def online_users():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.online == 1)
        else:
            users = User.select()\
                        .where(
                            User.gender == current_user.looking_for,
                            User.id.not_in(blist),
                            User.online == 1)
    except DoesNotExist:
        users = None
    return render_template(
        'main/users.html',
        users=users,
        dsc="Voici les utilisateurs actuellement en ligne.Envoyez vite un petit message à ceux qui vous font craquer.")


@main_blueprint.route('/yestaketime')
def yestaketime():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room2')
        else:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room2',
                            User.id.not_in(blist))
    except DoesNotExist:
        users = None
    return render_template('main/users.html', users=users)


@main_blueprint.route('/yestobedirect')
def yestobedirect():
    try:
        b = BlockList.select().where(BlockList.blocker == current_user.id)
        v = BlockList.select().where(BlockList.blocked_person == current_user.id)
        blist = [i.blocked_person.id for i in b]
        for p in v:
            blist.append(p.blocker.id)
        if not blist:
            users = User.select()\
                        .join(Profile)\
                        .where(
                            Profile.room == 'room1')
        else:
            users = User.select()\

project/user/views.py
from flask import (
    Blueprint, render_template, redirect,
    url_for, flash)
from flask_login import (
    login_user, login_required, logout_user, current_user)
from flask_babel import gettext
from project import bcrypt
from .forms import (
    RegistrationForm, LoginForm, ForgotForm,
    ChangePasswordForm, UpdatePasswordForm)
from project.models import User, IntegrityError, database, Slider, DoesNotExist
from project.tokens import generate_confirmation_token, confirm_token
from project.mailer import (
    welcome_mail, confirmation_email, reset_email)
from project.helpers import age

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            with database.transaction():
                user = User.create(
                    username=form.username.data,
                    email=form.email.data,
                    password_digest=bcrypt.generate_password_hash(form.password.data).decode('utf8'),
                    birthdate=form.birthdate.data,
                    location=form.location.data,
                    gender=form.gender.data,
                    looking_for=form.looking_for.data,
                    age=age(form.birthdate.data)
                )
                token = generate_confirmation_token(user.email)
                confirm_url = url_for(
                    'user.confirm_email', token=token, _external=True)
                welcome_mail(user.email, user.username)
                confirmation_email(
                    user.email,
                    user.username, confirm_url, user.email)
                login_user(user)
                return redirect(url_for('profile.new_profile'))
        except IntegrityError:
            raise ValueError(gettext('L\'utilisateur existe déjà'))
    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = User.select().where(User.email == form.email.data).get()
        except User.DoesNotExist:
            flash(gettext('incorrecte Adresse email ou Mot de passe.'))
        else:
            if user and bcrypt.check_password_hash(user.password_digest, form.password.data):
                login_user(user)
                if user.profile:
                    return redirect(url_for('main.index'))
                else:
                    return redirect(url_for('profile.new_profile'))
            else:
                flash(gettext('incorrecte Adresse email ou Mot de passe.'))
    return render_template('user/login.html', form=form)


@user_blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot():
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.select().where(User.email == form.email.data).get()
        token = generate_confirmation_token(user.email)

        user.reset_digest = token
        user.save()

        reset_url = url_for('user.new_password', token=token, _external=True)
        reset_email(user.email, user.username, reset_url)
        flash(gettext('Un e-mail de réinitialisation de mot de passe a été envoyé.'))
        return redirect(url_for('main.index'))
    return render_template('user/forgot.html', form=form)


@user_blueprint.route('/new_password/<token>', methods=['GET', 'POST'])
def new_password(token):
    email = confirm_token(token)
    user = User.select().where(User.email == email).get()

    if user.reset_digest is not None:
        form = ChangePasswordForm()
        if form.validate_on_submit():
            user = User.select().where(User.email == email).get()
            if user:
                user.password_digest = bcrypt.generate_password_hash(form.password.data)
                user.reset_digest = None
                user.save()

                login_user(user)
                flash(gettext('votre mot de passe a été changé'))
                return redirect(url_for('profile.profile'))
            else:
                flash(gettext('Le changement de mot de passe a échoué'))
                return redirect(url_for('profile.profile'))
        else:
            return render_template('user/change_password.html', form=form)
    else:
        flash(gettext('Impossible de réinitialiser votre mot de passe'))
    return redirect(url_for('main.index'))


@user_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    user = User.get(User.id == current_user.id)
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        user.password_digest = bcrypt.generate_password_hash(form.password.data)
        user.save()
        flash(gettext('votre mot de passe a été changé'))
        logout_user()
    return render_template('user/update_password.html', form=form)


@user_blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext('Le lien de confirmation est invalide ou a expiré.'))
    user = User.select().where(User.email == email).get()
    if user.confirmed:
        flash(gettext('Votre compte déjà confirmé.'))
    else:
        user.confirmed = True
        user.save()
    return redirect(url_for('main.index'))


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    confirmation_email(
        current_user.email, current_user.username, confirm_url)
    flash(gettext('Un nouvel e-mail de confirmation a été envoyé'))
    return redirect(url_for('profile.profile'))


@user_blueprint.route('/subscribe')
def subscribe():
    user = current_user.get()
    if user.notif == 0:
        user.notif = True
        user.save()
    return redirect(url_for('main.my_account'))


@user_blueprint.route('/unsbscribe')
def unsbscribe():
    user = current_user.get()
    if user.notif == 1:
        user.notif = False
        user.save()
    return redirect(url_for('main.my_account'))

project/templates/main/_cc_form.html
<form action="{{url_for('subscription.update_cc')}}" method="post" id="payment-form">
  <div class="form-row">
    <label for="card-element">
      {{ _('Carte de crédit ou Carte de débit') }}
    </label>
    <div id="card-element">
    </div>

    <div id="card-errors" role="alert"></div>
  </div>

  <div class="field">
    <button class="button">{{ _('Mise à jour')}}</button>              
  </div>
</form>

    <script>
      var stripe = Stripe('pk_test_3kCtgnOdq0e3Dmprk1tHUVmi');
      var elements = stripe.elements();

      var style = {
        base: {
          color: '#32325d',
          lineHeight: '18px',
          fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
          fontSmoothing: 'antialiased',
          fontSize: '16px',
          '::placeholder': {
            color: '#aab7c4'
          }
        },
        invalid: {
          color: '#fa755a',
          iconColor: '#fa755a'
        }
      };

      var card = elements.create('card', {style: style});
      card.mount('#card-element');
      card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          displayError.textContent = event.error.message;
        } else {
          displayError.textContent = '';
        }
      });
      var form = document.getElementById('payment-form');
      form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
          if (result.error) {
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
          } else {
            stripeTokenHandler(result.token);
          }
        });
      });

      function stripeTokenHandler(token) {
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);
        form.submit();
      }
    </script>

project/templates/main/_change_password.html
<form action="{{url_for('user.update_password')}}" method="POST">
  {{ form.csrf_token }}

  <div class="input-field col s3">
    {{ form.current_password() }}
    {{ form.current_password.label() }}
    {% for error in form.current_password.errors %}
      <span class="">{{ error }}</span>
    {% endfor %}
  </div>

  <div class="input-field col s3">
    {{ form.password() }}
    {{ form.password.label() }}
    {% for error in form.password.errors %}
      <span class="">{{ error }}</span>
    {% endfor %}
  </div>

  <div class="input-field col s3">
    {{ form.confirm() }}
    {{ form.confirm.label() }}
    {% for error in form.confirm.errors %}
      <span class="">{{ error }}</span>
    {% endfor %}
  </div>

  <div>
    <button type="submit" class="">Change Password</button>
  </div>
</form>

project/templates/main/article.html
{% extends 'layout.html' %}

{% block content %}
    
    <section class="section">
        <div class="columns">
            <div class="column is-three-quarters is-offset-1">
                <article class="content">
                    <h3 class="title">{{post.title}}</h3>
                    <p class="subtitle">{{post.post}}</p>
                </article>
                <div id="disqus_thread"></div>
            </div>
        </div>
    </section>

    <script>
        
        var disqus_config = function () {
        this.page.url = "{{request.url}}";  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = "{{request.path}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://yestomeetyou.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </script>

{% endblock %}

project/templates/main/blog.html
{% extends 'layout.html' %}

{% block title %}Bienvenue sur What About You ?{% endblock %}
{% block content %}
    
    <article class="section section-about">
        <p class="title is-3" style="color: #000 !important;">{{ _("Bienvenue sur What About You ?") }}</p>
        <p class="content">{{ _('What About You, c’est votre blog. Cet espace est dédié à votre personnalité. Vous y trouverez de nombreux sujets liés à l’amour et destinés à vous faire réagir. Exprimez vos idées pour que les autres membres découvrent votre caractère et aient envie d’en savoir plus sur vous.')}}</p>
    </article>

    <section class="section">
        <div class="columns">
            <div class="column is-three-fifths">
                {% if posts %}
                    {% for post in posts %}
                        <article class="content">
                            <h3>{{post.title}}</h3>
                            <p>{{post.post}}</p>
                            <a class="button text-white" href="{{url_for('main.article',id=post.id)}}">{{ _('lire suite')}}</a>
                            <div class="is-divider"></div>
                        </article>
                    {% endfor %}
                 {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

project/templates/main/contact.html
{% from 'macros/_render_input.html' import render_input %}
{% from 'macros/_render_textfield.html' import render_textfield %}

{% extends 'layout.html' %}

{% block content %}
    
    <section class="section">
        <div class="columns">
            <div class="column is-half is-offset-one-quarter">
                <p class="title is-3" style="color: #000 !important;">{{ _('Vous voulez contacter Yes To Meet You ?')}}</p>
                <p class="subtitle">{{ _('Nous sommes à votre écoute. Il suffit de remplir ce formulaire.')}}</p>
                <form action="{{url_for('main.contact')}}" method="POST">
                    {{ form.csrf_token }}
                    {{ render_input(form.nom)}}
                    {{ render_input(form.email)}}
                    {{ render_input(form.telephone)}}
                    {{ render_textfield(form.message)}}
                    <div class="field">
                        <input type="submit" class="button" value="{{ _('Envoyer') }}">
                    </div>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

project/templates/main/my_account.html
{% extends 'layout.html' %}

{% block content %}
    
    <section class="container">
        <div class="columns">
            <div class="column is-half">
                <div class="section">
                    <p class="title">{{ _('Mes donnés') }}</p>
                    <div class="is-divider"></div>
                    <p class="content">{{ _('Adresse Email')}}: {{ user.email }}</p>
                    {% if not user.confirmed %}
                        <p class="content">{{ _('Vous n\'avez pas confirmé votre compte.')}}<br> {{ _('Merci de confirmer votre adresse e-mail')}}</p>
                        <a class="text-white button" href="{{url_for('user.resend_confirmation')}}">Resend confirmation email</a>
                    {% endif %}
                    <p class="content" style="margin-top: 1rem;">
                        <a class="text-white button" href="{{url_for('user.update_password')}}">{{ _('Modifier votre mots de passe')}}</a>
                    </p>
                    <p class="content" >
                        <a class="text-red" href="{{ url_for('report.blocklist')}}">{{ _('Block Liste')}}</a>
                    </p>
                    {% if profile.gift == 1 %}
                        <p class="content">
                            <a class="text-red" href="{{url_for('profile.update_gift')}}">{{ _('Je ne veux plus recevoir de cadeau.')}}</a>
                        </p>
                    {% else %}
                        <p class="content">
                            <a class="text-red" href="{{url_for('profile.update_gift')}}">{{ _('J\'aimerais recevoir des cadeaux.')}}</a>
                        </p>
                    {% endif %}
                    {% if address != None %}
                        <p class="content">
                            <a class="text-red" href="{{url_for('profile.update_address')}}">{{ _('Mettez à jour votre adresse')}}</a>
                        </p>
                    {% else %}
                        <p class="content">
                            <a class="text-red" href="{{url_for('profile.address')}}">{{ _('Ajoutez votre adresse')}}</a>
                        </p>
                    {% endif%}
                    <article>
                        <p class="title" style="color: #000 !important;">{{ _('Ne ratez rien !')}}</p>
                        <p class="subtitle">{{ _('Yes To Meet You peut vous avertir quand il se passe quelque chose.')}}</p>
                    </article>
                    {% if user.notif == True %}
                        <p class="content">
                            <a href="{{url_for('user.unsbscribe')}}" class="text-red">{{ _('Je ne veux plus recevoir des notifications')}}</a>
                        </p>
                    {% else %}
                        <p class="content">
                            <a href="{{url_for('user.subscribe')}}" class="text-red">{{ _('Je veux recevoir des notifications.')}}</a>
                        </p>
                    {% endif%}
                </div>
            </div>

            <div class="column">
                <div class="section">
                    <p class="title">{{ _('Mon abonnement') }}</p>
                    <div class="is-divider"></div>
                    {% if sub %}
                        <p class="content"> {{ _('Plan d\'abonnement')}} : {{ sub.plan | upper }}</p>
                        <p>{{ _('Expire à')}}: {{ sub.expire_at }}</p>
                        <a href="{{url_for('subscription.cancel_subscription')}}">{{ _('Annuler l\'abonnement')}}</a>
                        <div>
                            {% include 'main/_cc_form.html'%}
                        </div>
                        
                    {% else %}
                        <!-- <p>{{ _('Pas d\'abonnement actif!')}}</p>
                        <a class='button' href="{{url_for('subscription.plan')}}">{{ _('je m\'abonne')}}</a> -->
                        <p>{{ _('Profitez-en, Yes To Meet You est gratuit jusqu’en <strong>avril 2018.</strong>')}}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

project/templates/main/search.html
{% from 'macros/_render_field.html' import render_field %}
{% extends 'layout.html' %}

{% block content %}
        
    <section class="container">
        <div class="columns" style="margin-top: 40px;">
            <div class="column is-two-fifths is-offset-one-quarter">
                <h3 class="title has-text-centered">Recherche</h3>
                <p>{{ _('Yes To Meet You c’est une autre façon de faire des rencontres. Mais comme point de départ, une petite recherche classique, ce n’est pas si mal. ☺')}}</p>
                <section class="box">
                    <form action="{{url_for('main.search')}}" method="POST">
                        {{ form.csrf_token }}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                                <label class="label">{{ _('Age')}}</label>
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    {{ render_field(form.age_min)}}
                                </div>
                                <div class="field">
                                    {{ render_field(form.age_max)}}
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            {{ render_field(form.gender)}}
                        </div>
                        <div class="field has-text-centered">
                            <input type="submit" class="button" value="{{ _('Recherche')}}">
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </section>

{% endblock %}

project/templates/main/visit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="columns users_list">
    {% if visit_list != None %}
        {% for v in visit_list %}
                <div class="column is-one-quarter">
                <div class="card">
                    <div class="card-photo">
                        {% for photo in v.visitor.photos %}
                            {% if photo.default and not photo.private %}
                                <figure class="image is-4by3">
                                    <img src="{{photo.url}}" width="300">
                                </figure>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-content">
                        <div class="media-content">
                            <p class="title is-4"><a href="{{url_for('main.profile',username=v.visitor.username)}}">{{ v.visitor.username}}</a></p>
                            <p class="subtitle is-6">{{ age(v.visitor.birthdate) }} years old | {{ v.visitor.location }}</p>
                        </div>
                    </div>       
                </div>
                </div>
        {% endfor %}
    {% else %}
        <section class="container">
            <p>{{ _('Rhooo, vous n’avez pas encore eu de visites pour le moment. ☹ Contactez des membres et commencez une belle relation. ☺')}}</p>            
        </section>
    {% endif %}
    </div>
{% endblock %}