project/user/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, PasswordField, SubmitField,
    DateField, SelectField, BooleanField)
from wtforms.validators import (
    DataRequired, EqualTo, Email,
    ValidationError, Length)
from flask_babel import gettext

from project.models import User
from project import current_user, bcrypt


def email_exist(form, field):
    if User.select().where(User.email == field.data).exists():
        raise ValidationError('Vous êtes déjà inscrit')


def username_exist(form, field):
    if User.select().where(User.username == field.data).exists():
        raise ValidationError('Pseudo déjà pris')


def email_not_exist(form, field):
    if not User.select().where(User.email == field.data):
        raise ValidationError('Adresse Email n\'existe pas')


def password_does_not_match(form, field):
    if not bcrypt.check_password_hash(current_user.password_digest, field.data):
        raise ValidationError(gettext('mot de passe incorrect'))


class RegistrationForm(FlaskForm):
    birthdate = DateField(
        gettext('Date de naissance'),
        format='%m/%d/%Y',
        validators=[DataRequired()],
        render_kw={"placeholder": gettext('Date de naissance')})
    gender = SelectField(
        gettext('Je suis'),
        choices=[('men', gettext('un homme')), ('women', gettext('une femme'))],
        validators=[DataRequired()])
    looking_for = SelectField(
        gettext('cherchant'),
        choices=[('women', gettext('une femme')), ('men', gettext('un homme'))],
        validators=[DataRequired()])
    location = StringField(gettext('Ville'), validators=[DataRequired()])
    username = StringField(
        gettext('Pseudo'),
        validators=[DataRequired(), Length(min=6), username_exist],
        render_kw={"placeholder": gettext('Pseudo')})
    email = StringField(
        gettext('Adresse Email'),
        validators=[DataRequired(), Email(), email_exist],
        render_kw={"placeholder": gettext('Adresse Email')})
    password = PasswordField(
        gettext('Mot de passe'),
        validators=[
            DataRequired(),
            EqualTo('confirm', message="Password must match"),
            Length(min=6)
        ],
        render_kw={"placeholder": gettext('6 caractères alphanumériques minimum')})
    confirm = PasswordField(gettext('Confirmation de mot de passe'))
    checkbox = BooleanField(
        gettext('Agree'), default=False, validators=[DataRequired()])
    submit = SubmitField(gettext("Continuer l'inscription"))


class LoginForm(FlaskForm):
    email = StringField(
        gettext('Adresse Email'), validators=[DataRequired(), Email()])
    password = PasswordField(
        gettext('Mot de passe'), validators=[DataRequired()])
    submit = SubmitField(gettext('Se connecter'))


class ForgotForm(FlaskForm):
    email = StringField(
        gettext('Adresse Email'),
        validators=[
            DataRequired(), Email(), email_not_exist
        ])


class ChangePasswordForm(FlaskForm):
    password = PasswordField(
        gettext('Mot de passe'), validators=[DataRequired(), Length(min=6)])
    confirm = PasswordField(
        gettext('Confirmation de mot de passe'),
        validators=[
            DataRequired(),
            EqualTo('password', message='Password must match')
        ])


class UpdatePasswordForm(FlaskForm):
    current_password = PasswordField(
        gettext('Mot de passe actuel'),
        validators=[DataRequired(), password_does_not_match])
    password = PasswordField(
        gettext('Mot de passe'), validators=[DataRequired(), Length(min=6)])
    confirm = PasswordField(
        gettext('Confirmation de mot de passe'),
        validators=[
            DataRequired(),
            EqualTo('password', message='Password must match')
        ])

project/user/views.py
from flask import (
    Blueprint, render_template, redirect,
    url_for, flash)
from flask_login import (
    login_user, login_required, logout_user, current_user)
from flask_babel import gettext
from project import bcrypt
from .forms import (
    RegistrationForm, LoginForm, ForgotForm,
    ChangePasswordForm, UpdatePasswordForm)
from project.models import User, IntegrityError, database, Slider, DoesNotExist
from project.tokens import generate_confirmation_token, confirm_token
from project.mailer import (
    welcome_mail, confirmation_email, reset_email)
from project.helpers import age

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            with database.transaction():
                user = User.create(
                    username=form.username.data,
                    email=form.email.data,
                    password_digest=bcrypt.generate_password_hash(form.password.data).decode('utf8'),
                    birthdate=form.birthdate.data,
                    location=form.location.data,
                    gender=form.gender.data,
                    looking_for=form.looking_for.data,
                    age=age(form.birthdate.data)
                )
                token = generate_confirmation_token(user.email)
                confirm_url = url_for(
                    'user.confirm_email', token=token, _external=True)
                welcome_mail(user.email, user.username)
                confirmation_email(
                    user.email,
                    user.username, confirm_url, user.email)
                login_user(user)
                return redirect(url_for('profile.new_profile'))
        except IntegrityError:
            raise ValueError(gettext('L\'utilisateur existe déjà'))
    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = User.select().where(User.email == form.email.data).get()
        except User.DoesNotExist:
            flash(gettext('incorrecte Adresse email ou Mot de passe.'))
        else:
            if user and bcrypt.check_password_hash(user.password_digest, form.password.data):
                login_user(user)
                if user.profile:
                    return redirect(url_for('main.index'))
                else:
                    return redirect(url_for('profile.new_profile'))
            else:
                flash(gettext('incorrecte Adresse email ou Mot de passe.'))
    return render_template('user/login.html', form=form)


@user_blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot():
    form = ForgotForm()
    if form.validate_on_submit():
        user = User.select().where(User.email == form.email.data).get()
        token = generate_confirmation_token(user.email)

        user.reset_digest = token
        user.save()

        reset_url = url_for('user.new_password', token=token, _external=True)
        reset_email(user.email, user.username, reset_url)
        flash(gettext('Un e-mail de réinitialisation de mot de passe a été envoyé.'))
        return redirect(url_for('main.index'))
    return render_template('user/forgot.html', form=form)


@user_blueprint.route('/new_password/<token>', methods=['GET', 'POST'])
def new_password(token):
    email = confirm_token(token)
    user = User.select().where(User.email == email).get()

    if user.reset_digest is not None:
        form = ChangePasswordForm()
        if form.validate_on_submit():
            user = User.select().where(User.email == email).get()
            if user:
                user.password_digest = bcrypt.generate_password_hash(form.password.data)
                user.reset_digest = None
                user.save()

                login_user(user)
                flash(gettext('votre mot de passe a été changé'))
                return redirect(url_for('profile.profile'))
            else:
                flash(gettext('Le changement de mot de passe a échoué'))
                return redirect(url_for('profile.profile'))
        else:
            return render_template('user/change_password.html', form=form)
    else:
        flash(gettext('Impossible de réinitialiser votre mot de passe'))
    return redirect(url_for('main.index'))


@user_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    user = User.get(User.id == current_user.id)
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        user.password_digest = bcrypt.generate_password_hash(form.password.data)
        user.save()
        flash(gettext('votre mot de passe a été changé'))
        logout_user()
    return render_template('user/update_password.html', form=form)


@user_blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash(gettext('Le lien de confirmation est invalide ou a expiré.'))
    user = User.select().where(User.email == email).get()
    if user.confirmed:
        flash(gettext('Votre compte déjà confirmé.'))
    else:
        user.confirmed = True
        user.save()
    return redirect(url_for('main.index'))


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    confirmation_email(
        current_user.email, current_user.username, confirm_url)
    flash(gettext('Un nouvel e-mail de confirmation a été envoyé'))
    return redirect(url_for('profile.profile'))


@user_blueprint.route('/subscribe')
def subscribe():
    user = current_user.get()
    if user.notif == 0:
        user.notif = True
        user.save()
    return redirect(url_for('main.my_account'))


@user_blueprint.route('/unsbscribe')
def unsbscribe():
    user = current_user.get()
    if user.notif == 1:
        user.notif = False
        user.save()
    return redirect(url_for('main.my_account'))

project/templates/user/activate.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{{ _('Confirmez votre e-mail')}}</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      .btn-primary table td:hover {
        background-color: #731526 !important;
      }
      .btn-primary a:hover {
        background-color: #731526 !important;
        border-color: #731526 !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">{{ _('YES ! Plus qu’un clic.') }}</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px; border: 2px solid #E3E4E5;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <img src="https://s3.eu-central-1.amazonaws.com/yestomeetyou/logo.png" style="display: block; margin: auto;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;">{{username}},</p>
                        <h3 style="font-family: sans-serif; font-size: 18px; font-weight: bold; margin: 0; margin-bottom: 15px;">{{ _('YES ! Plus qu’un clic.') }}</h3>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">{{ _('Votre inscription est presque validée. Cliquez sur le lien/le bouton ci-dessous pour la finaliser.')}}</p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">{{ _('Vous vous êtes inscrit sur le site Yes To Meet You en fournissant   l’adresse e-mail :')}} {{email}}</p>
                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;">
                          <tbody>
                            <tr>
                              <td align="left" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;">
                                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;">
                                  <tbody>
                                    <tr>
                                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top; background-color: #A7223A; border-radius: 5px; text-align: center;"> <a href="{{ confirm_url }}" target="_blank" style="display: inline-block; color: #ffffff; background-color: #A7223A; border: solid 1px #A7223A; border-radius: 5px; box-sizing: border-box; cursor: pointer; text-decoration: none; font-size: 14px; font-weight: bold; margin: 0; padding: 12px 25px; text-transform: capitalize; border-color: #A7223A;">{{ _('Je confirme mon e-mail')}}</a> </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                        
                        <p>{{ _('Merci') }}</p>
                        <p>{{ _('L’équipe Yes To Meet You') }}</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            <!-- END MAIN CONTENT AREA -->
            </table>
          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

project/templates/user/change_password.html
{% from 'macros/_render_input.html' import render_input %}
{% extends 'layout.html' %}

{% block content %}
    <section class="hero">
    <div class="hero-body">
      <div class="container has-text-centered">
        <div class="column is-4 is-offset-4">
          <h3 class="title has-text-grey">{{ _('Changer le mot de passe')}}</h3>
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
              <div class="notification is-danger">
                <button class="delete"></button>
                {{ message }}
              </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <div class="box">
            <form method="POST" action="">
              {{ form.csrf_token }}
              {{ render_input(form.password) }}
              {{ render_input(form.confirm) }}

              <div class="field">
                <button type="submit" class="button">{{ _('Changer le mot de passe')}}</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

project/templates/user/forgot.html
{% from 'macros/_render_input.html' import render_input %}
{% extends 'layout.html' %}

{% block title %}Réinitialiser le mot de passe{% endblock %}
{% block content %}

    <section class="hero">
    <div class="hero-body">
      <div class="container">
        <div class="column is-4 is-offset-4">
          <h3 class="title has-text-grey">{{ _('Réinitialiser le mot de passe')}}</h3>
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
              <div class="notification is-danger">
                <button class="delete"></button>
                {{ message }}
              </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <div class="box">
            <form method="POST" action="{{ url_for('user.forgot') }}">
              {{ form.csrf_token }}
              {{ render_input(form.email) }}
              <div class="field">
                <button type="submit" class="button">{{ _('Réinitialiser')}}</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

project/templates/user/login.html
{% from 'macros/_render_input.html' import render_input %}
{% extends 'layout.html' %}
{% block title %}{{ _('Déjà membre')}}{% endblock %}
{% block content %}
    <section class="hero">
    <div class="hero-body">
      <div class="container ">
        <div class="column is-4 is-offset-4">
          <h3 class="title has-text-grey">{{ _('Se connecter')}}</h3>
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}
              <div class="notification is-danger">
                <button class="delete"></button>
                {{ message }}
              </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          <div class="box">
            <form method="POST" action="{{ url_for('user.login') }}">
              {{ form.csrf_token }}
              {{ render_input(form.email) }}
              {{ render_input(form.password) }}
              {{ form.submit(class="button is-block is-large") }}
            </form>
          </div>
          <p class="has-text-grey">
            <a href="{{url_for('user.forgot')}}" class="left text-red">{{ _('Mots de passe oublié?') }}</a> &nbsp;·&nbsp;
          </p>
        </div>
      </div>
    </div>
  </section>
    
{% endblock %}

project/templates/user/register.html
{% extends 'layout.html' %}
{% block title %}{{ _('S\'enregistrer') }}{% endblock %}
{% block content %}
    <div class="columns is-mobile">
        <div class="column is-half-desktop is-offset-one-quarter-desktop">
            <form action="" method="POST" class="box">
                 {{ form.csrf_token }}
                 <div class="field is-horizontal">
                    <div class="field-body">
                        <div class="field">
                            {{ form.username.label(class='label')}}
                            {{ form.username(class='input') }}
                            {% for error in form.username.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="field">
                            {{ form.email.label(class='label')}}
                            {{ form.email(class='input')}}
                            {% for error in form.email.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                 </div>
                 <div class="field is-horizontal">
                     <div class="field-body">
                        <div class="field">
                            {{ form.password.label(class='label')}}
                            {{ form.password(class='input')}}
                            {% for error in form.password.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                         </div>
                         <div class="field">
                            {{ form.confirm.label(class='label')}}
                            {{ form.confirm(class='input')}}
                            {% for error in form.confirm.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                         </div>
                    </div>
                 </div>
                 <div class="field is-horizontal">
                     <div class="field-body">
                        <div class="field">
                            {{ form.location.label(class='label')}}
                            {{ form.location(class="input") }}
                            {% for error in form.location.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                         <div class="field">
                            {{ form.birthdate.label(class='label')}}
                            {{ form.birthdate(class="input") }}
                            {% for error in form.birthdate.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                            <p id = "berror" class="help is-danger" style="display: none;">{{ _('Vous devez avoir min. 18 ans pour nous rejoindre.')}}</p>
                        </div>
                    </div>
                 </div>
                 <div class="field is-horizontal">
                     <div class="field-body">
                        <div class="field">
                             {{ form.gender.label(class="label") }}
                            <div class="select">
                              {{ form.gender() }}
                            </div>
                            {% for error in form.gender.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                         </div>
                         <div class="field">
                            {{ form.looking_for.label(class="label") }}
                            <div class="select">
                              {{ form.looking_for() }}          
                            </div>
                            {% for error in form.looking_for.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                         </div>
                    </div>
                 </div>
                 <div class="field is-horizontal">
                     <div class="field">
                        <label class="checkbox">
                            {{ form.checkbox(class="checkbox") }}
                            <span>{{ _('Je certifie être majeur(e), <a class="text-red" href="/conditions">j’ai lu et j’accepte les CGU, la politique sur la vie privée de yestomeetyou et services décrits</a>') }}</span>
                            {% for error in form.checkbox.errors %}
                              <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        </label>
                     </div>
                </div>
                <div class="field is-horizontal">
                    <div class="field-body">
                        <div class="field">
                            {{ form.submit(class='button is-block is-large')}}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAaz-M_rn74nLpqMm7s5o-veRDLNBpjRc&libraries=places&language=fr"></script>
    <script src="{{ url_for('static', filename='js/map.js') }}" ></script>
{% endblock %}

project/templates/user/update_password.html
{% extends 'layout.html' %}

{% block title %}Changer mots de passe{% endblock %}
{% block content %}

  <div class="container">
    <div class="column is-4 is-offset-4">
      <h3 class="title has-text-grey">{{ _('Changer mots de passe')}}</h3>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
          <div class="notification is-danger">
            <button class="delete"></button>
            {{ message }}
          </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="box">
        <form action="{{url_for('user.update_password')}}" method="POST">
          {{ form.csrf_token }}

          <div class="field">
            {{ form.current_password.label(class='label') }}
            {{ form.current_password(class='input') }}
            {% for error in form.current_password.errors %}
              <p class="help is-danger">{{ error }}</p>
            {% endfor %}
          </div>

          <div class="field">
            {{ form.password.label(class='label') }}
            {{ form.password(class='input') }}
            {% for error in form.password.errors %}
              <span class="help is-danger">{{ error }}</span>
            {% endfor %}
          </div>

          <div class="field">
            {{ form.confirm.label(class='label') }}
            {{ form.confirm(class='input') }}
            {% for error in form.confirm.errors %}
              <span class="help is-danger">{{ error }}</span>
            {% endfor %}
          </div>

          <div class="field">
            <button type="submit" class="button">{{ _('Changer mots de passe')}}</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>

{% endblock %}